name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: '2.0.72'
          inlineScript: |
            az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            az storage blob upload-batch -s . -d \$web --account-name jswhawkes

      - name: Purge Azure CDN (Optional)
        uses: azure/CLI@v1
        with:
          azcliversion: '2.0.72'
          inlineScript: |
            az cdn endpoint purge -g jswhawkes -n jswhawkes --profile-name jswhawkesCDN --content-paths '/*'

      - name: Logout from Azure
        run: az logout
