name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: '2.30.0'
          inlineScript: |
            az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            az storage blob upload-batch --account-name jswhawkes -d \$web -s . 

      - name: Purge Azure CDN (Optional)
        uses: azure/CLI@v1
        with:
          azcliversion: '2.30.0'
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "jswhawkesCDN" --name "jswhawkes" --resource-group "jswhawkes"

      - name: Logout from Azure
        run: az logout
