name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Upload to Azure Storage
      run: |
        az storage blob upload-batch -d \$web --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} -s .

    - name: Purge Azure CDN
      run: |
        az cdn endpoint purge -g jswhawkes -n jswhawkes --profile-name jswhawkesCDN --content-paths '/*'
