name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clear runner temp directory
      run: rm -rf /home/runner/work/_temp

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20'

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'
        node-version: '20'

    - name: Login to Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Upload to Azure Storage
      run: |
        az storage blob upload-batch -d \$web --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} -s .

    - name: Purge Azure CDN (Optional)
      run: |
        az cdn endpoint purge -g jswhawkes -n jswhawkes --profile-name jswhawkesCDN --content-paths '/*'
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
